name: Code Review with AI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Validate Secret Tokens
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ] || [ -z "${{ secrets.OPEN_ARENA_TOKEN }}" ]; then
            echo "Missing required environment variables (GH_TOKEN or OPEN_ARENA_TOKEN). Exiting."
            exit 1
          fi
          echo "All required environment variables are available."

      - name: List installed packages
        run: pip list

      - name: Run Code Review with AI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPEN_ARENA_TOKEN: ${{ secrets.OPEN_ARENA_TOKEN }}
          GITHUB_PR_URL: ${{ github.event.pull_request.url }}
          WORKFLOW_ID: "80f448d2-fd59-440f-ba24-ebc3014e1fdf"  # Replace with your actual workflow ID
        run: python3 scripts/ai_code_reviewer.py
